add Name::display_name
estokes/libgssapi pull request #11
Opened 2022-07-06 15:54 UTC by aaronjanse

This wraps [`gss_display_name`](https://docs.rs/libgssapi-sys/latest/libgssapi_sys/fn.gss_display_name.html) in a way that lets the user handle errors. It also lets the user do UTF-8 decoding themselves instead of automatically calling [`String::from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy).

2022-07-06 15:58 UTC, estokes commented
Cool! I will review.

2022-07-06 16:07 UTC, aaronjanse commented
Thank you, and thanks for writing this library! It's been pleasant to work with once I got my build environment figured out.

2022-07-08 15:49 UTC, estokes requested changes
fmt::Debug should call display_name instead of reimplementing the same code.

2022-07-11 15:58 UTC, aaronjanse commented
Good call. Done in 70e8b31a2964641c8b130efebdc86528bba1e027

2022-07-12 13:39 UTC, merged